// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TechnicalIndicators.proto

package io.gbdevw.colibri.domain.technicalindicators;

public final class TechnicalIndicators {
  private TechnicalIndicators() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MACDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:colibri.MACD)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The enum numeric value on the wire for unit.
     */
    int getUnitValue();
    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The unit.
     */
    io.gbdevw.colibri.domain.utils.Utils.Currency getUnit();

    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The enum numeric value on the wire for quote.
     */
    int getQuoteValue();
    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The quote.
     */
    io.gbdevw.colibri.domain.utils.Utils.Currency getQuote();

    /**
     * <code>double macd = 4;</code>
     * @return The macd.
     */
    double getMacd();

    /**
     * <code>double signal = 5;</code>
     * @return The signal.
     */
    double getSignal();
  }
  /**
   * <pre>
   * Moving Average Convergence-Divergence (ex : Slow EMA : 26, Fast EMA : 10, Signal : 9)
   * timestamp : The number of milliseconds from the epoch of 1970-01-01T00:00:00Z. - When the indicator is produced
   * unit : Unit currency (Ex : BTC, ETH)
   * quote : Quote currency (Ex : EUR, USD)
   * macd : MACD value (slow - fast)
   * signal : Signal value
   * </pre>
   *
   * Protobuf type {@code colibri.MACD}
   */
  public  static final class MACD extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:colibri.MACD)
      MACDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MACD.newBuilder() to construct.
    private MACD(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MACD() {
      unit_ = 0;
      quote_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MACD();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MACD(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              unit_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              quote_ = rawValue;
              break;
            }
            case 33: {

              macd_ = input.readDouble();
              break;
            }
            case 41: {

              signal_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_MACD_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_MACD_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD.class, io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int UNIT_FIELD_NUMBER = 2;
    private int unit_;
    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The enum numeric value on the wire for unit.
     */
    public int getUnitValue() {
      return unit_;
    }
    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The unit.
     */
    public io.gbdevw.colibri.domain.utils.Utils.Currency getUnit() {
      @SuppressWarnings("deprecation")
      io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(unit_);
      return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
    }

    public static final int QUOTE_FIELD_NUMBER = 3;
    private int quote_;
    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The enum numeric value on the wire for quote.
     */
    public int getQuoteValue() {
      return quote_;
    }
    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The quote.
     */
    public io.gbdevw.colibri.domain.utils.Utils.Currency getQuote() {
      @SuppressWarnings("deprecation")
      io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(quote_);
      return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
    }

    public static final int MACD_FIELD_NUMBER = 4;
    private double macd_;
    /**
     * <code>double macd = 4;</code>
     * @return The macd.
     */
    public double getMacd() {
      return macd_;
    }

    public static final int SIGNAL_FIELD_NUMBER = 5;
    private double signal_;
    /**
     * <code>double signal = 5;</code>
     * @return The signal.
     */
    public double getSignal() {
      return signal_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeUInt64(1, timestamp_);
      }
      if (unit_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        output.writeEnum(2, unit_);
      }
      if (quote_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        output.writeEnum(3, quote_);
      }
      if (macd_ != 0D) {
        output.writeDouble(4, macd_);
      }
      if (signal_ != 0D) {
        output.writeDouble(5, signal_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      if (unit_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, unit_);
      }
      if (quote_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, quote_);
      }
      if (macd_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, macd_);
      }
      if (signal_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, signal_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD)) {
        return super.equals(obj);
      }
      io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD other = (io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (unit_ != other.unit_) return false;
      if (quote_ != other.quote_) return false;
      if (java.lang.Double.doubleToLongBits(getMacd())
          != java.lang.Double.doubleToLongBits(
              other.getMacd())) return false;
      if (java.lang.Double.doubleToLongBits(getSignal())
          != java.lang.Double.doubleToLongBits(
              other.getSignal())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + unit_;
      hash = (37 * hash) + QUOTE_FIELD_NUMBER;
      hash = (53 * hash) + quote_;
      hash = (37 * hash) + MACD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMacd()));
      hash = (37 * hash) + SIGNAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSignal()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Moving Average Convergence-Divergence (ex : Slow EMA : 26, Fast EMA : 10, Signal : 9)
     * timestamp : The number of milliseconds from the epoch of 1970-01-01T00:00:00Z. - When the indicator is produced
     * unit : Unit currency (Ex : BTC, ETH)
     * quote : Quote currency (Ex : EUR, USD)
     * macd : MACD value (slow - fast)
     * signal : Signal value
     * </pre>
     *
     * Protobuf type {@code colibri.MACD}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:colibri.MACD)
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_MACD_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_MACD_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD.class, io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD.Builder.class);
      }

      // Construct using io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        unit_ = 0;

        quote_ = 0;

        macd_ = 0D;

        signal_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_MACD_descriptor;
      }

      @java.lang.Override
      public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD getDefaultInstanceForType() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD.getDefaultInstance();
      }

      @java.lang.Override
      public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD build() {
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD buildPartial() {
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD result = new io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD(this);
        result.timestamp_ = timestamp_;
        result.unit_ = unit_;
        result.quote_ = quote_;
        result.macd_ = macd_;
        result.signal_ = signal_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD) {
          return mergeFrom((io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD other) {
        if (other == io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.unit_ != 0) {
          setUnitValue(other.getUnitValue());
        }
        if (other.quote_ != 0) {
          setQuoteValue(other.getQuoteValue());
        }
        if (other.getMacd() != 0D) {
          setMacd(other.getMacd());
        }
        if (other.getSignal() != 0D) {
          setSignal(other.getSignal());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 1;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int unit_ = 0;
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @return The enum numeric value on the wire for unit.
       */
      public int getUnitValue() {
        return unit_;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @param value The enum numeric value on the wire for unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnitValue(int value) {
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @return The unit.
       */
      public io.gbdevw.colibri.domain.utils.Utils.Currency getUnit() {
        @SuppressWarnings("deprecation")
        io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(unit_);
        return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @param value The unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnit(io.gbdevw.colibri.domain.utils.Utils.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        unit_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnit() {
        
        unit_ = 0;
        onChanged();
        return this;
      }

      private int quote_ = 0;
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @return The enum numeric value on the wire for quote.
       */
      public int getQuoteValue() {
        return quote_;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @param value The enum numeric value on the wire for quote to set.
       * @return This builder for chaining.
       */
      public Builder setQuoteValue(int value) {
        quote_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @return The quote.
       */
      public io.gbdevw.colibri.domain.utils.Utils.Currency getQuote() {
        @SuppressWarnings("deprecation")
        io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(quote_);
        return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @param value The quote to set.
       * @return This builder for chaining.
       */
      public Builder setQuote(io.gbdevw.colibri.domain.utils.Utils.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        quote_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuote() {
        
        quote_ = 0;
        onChanged();
        return this;
      }

      private double macd_ ;
      /**
       * <code>double macd = 4;</code>
       * @return The macd.
       */
      public double getMacd() {
        return macd_;
      }
      /**
       * <code>double macd = 4;</code>
       * @param value The macd to set.
       * @return This builder for chaining.
       */
      public Builder setMacd(double value) {
        
        macd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double macd = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMacd() {
        
        macd_ = 0D;
        onChanged();
        return this;
      }

      private double signal_ ;
      /**
       * <code>double signal = 5;</code>
       * @return The signal.
       */
      public double getSignal() {
        return signal_;
      }
      /**
       * <code>double signal = 5;</code>
       * @param value The signal to set.
       * @return This builder for chaining.
       */
      public Builder setSignal(double value) {
        
        signal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double signal = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignal() {
        
        signal_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:colibri.MACD)
    }

    // @@protoc_insertion_point(class_scope:colibri.MACD)
    private static final io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD();
    }

    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MACD>
        PARSER = new com.google.protobuf.AbstractParser<MACD>() {
      @java.lang.Override
      public MACD parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MACD(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MACD> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MACD> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.MACD getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ROCOrBuilder extends
      // @@protoc_insertion_point(interface_extends:colibri.ROC)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The enum numeric value on the wire for unit.
     */
    int getUnitValue();
    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The unit.
     */
    io.gbdevw.colibri.domain.utils.Utils.Currency getUnit();

    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The enum numeric value on the wire for quote.
     */
    int getQuoteValue();
    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The quote.
     */
    io.gbdevw.colibri.domain.utils.Utils.Currency getQuote();

    /**
     * <code>uint32 xPeriod = 4;</code>
     * @return The xPeriod.
     */
    int getXPeriod();

    /**
     * <code>double roc = 6;</code>
     * @return The roc.
     */
    double getRoc();

    /**
     * <code>double resistance = 7;</code>
     * @return The resistance.
     */
    double getResistance();

    /**
     * <code>double support = 8;</code>
     * @return The support.
     */
    double getSupport();
  }
  /**
   * <pre>
   * Rate Of Change
   * timestamp : The number of milliseconds from the epoch of 1970-01-01T00:00:00Z. - When the indicator is produced
   * unit : Unit currency (Ex : BTC, ETH)
   * quote : Quote currency (Ex : EUR, USD)
   * xPeriod : Number of OHLCV used to produce the indicator
   * roc : ROC value for the period (decimal, 0.01 stands for 1%)
   * resistance : Maximal closing price in quote currency for one unit of unit currency for the period
   * support : Minimal closing price in quote currency for one unit of unit currency for the period
   * </pre>
   *
   * Protobuf type {@code colibri.ROC}
   */
  public  static final class ROC extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:colibri.ROC)
      ROCOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ROC.newBuilder() to construct.
    private ROC(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ROC() {
      unit_ = 0;
      quote_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ROC();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ROC(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              unit_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              quote_ = rawValue;
              break;
            }
            case 32: {

              xPeriod_ = input.readUInt32();
              break;
            }
            case 49: {

              roc_ = input.readDouble();
              break;
            }
            case 57: {

              resistance_ = input.readDouble();
              break;
            }
            case 65: {

              support_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_ROC_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_ROC_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC.class, io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int UNIT_FIELD_NUMBER = 2;
    private int unit_;
    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The enum numeric value on the wire for unit.
     */
    public int getUnitValue() {
      return unit_;
    }
    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The unit.
     */
    public io.gbdevw.colibri.domain.utils.Utils.Currency getUnit() {
      @SuppressWarnings("deprecation")
      io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(unit_);
      return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
    }

    public static final int QUOTE_FIELD_NUMBER = 3;
    private int quote_;
    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The enum numeric value on the wire for quote.
     */
    public int getQuoteValue() {
      return quote_;
    }
    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The quote.
     */
    public io.gbdevw.colibri.domain.utils.Utils.Currency getQuote() {
      @SuppressWarnings("deprecation")
      io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(quote_);
      return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
    }

    public static final int XPERIOD_FIELD_NUMBER = 4;
    private int xPeriod_;
    /**
     * <code>uint32 xPeriod = 4;</code>
     * @return The xPeriod.
     */
    public int getXPeriod() {
      return xPeriod_;
    }

    public static final int ROC_FIELD_NUMBER = 6;
    private double roc_;
    /**
     * <code>double roc = 6;</code>
     * @return The roc.
     */
    public double getRoc() {
      return roc_;
    }

    public static final int RESISTANCE_FIELD_NUMBER = 7;
    private double resistance_;
    /**
     * <code>double resistance = 7;</code>
     * @return The resistance.
     */
    public double getResistance() {
      return resistance_;
    }

    public static final int SUPPORT_FIELD_NUMBER = 8;
    private double support_;
    /**
     * <code>double support = 8;</code>
     * @return The support.
     */
    public double getSupport() {
      return support_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeUInt64(1, timestamp_);
      }
      if (unit_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        output.writeEnum(2, unit_);
      }
      if (quote_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        output.writeEnum(3, quote_);
      }
      if (xPeriod_ != 0) {
        output.writeUInt32(4, xPeriod_);
      }
      if (roc_ != 0D) {
        output.writeDouble(6, roc_);
      }
      if (resistance_ != 0D) {
        output.writeDouble(7, resistance_);
      }
      if (support_ != 0D) {
        output.writeDouble(8, support_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      if (unit_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, unit_);
      }
      if (quote_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, quote_);
      }
      if (xPeriod_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, xPeriod_);
      }
      if (roc_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, roc_);
      }
      if (resistance_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, resistance_);
      }
      if (support_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, support_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC)) {
        return super.equals(obj);
      }
      io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC other = (io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (unit_ != other.unit_) return false;
      if (quote_ != other.quote_) return false;
      if (getXPeriod()
          != other.getXPeriod()) return false;
      if (java.lang.Double.doubleToLongBits(getRoc())
          != java.lang.Double.doubleToLongBits(
              other.getRoc())) return false;
      if (java.lang.Double.doubleToLongBits(getResistance())
          != java.lang.Double.doubleToLongBits(
              other.getResistance())) return false;
      if (java.lang.Double.doubleToLongBits(getSupport())
          != java.lang.Double.doubleToLongBits(
              other.getSupport())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + unit_;
      hash = (37 * hash) + QUOTE_FIELD_NUMBER;
      hash = (53 * hash) + quote_;
      hash = (37 * hash) + XPERIOD_FIELD_NUMBER;
      hash = (53 * hash) + getXPeriod();
      hash = (37 * hash) + ROC_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRoc()));
      hash = (37 * hash) + RESISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getResistance()));
      hash = (37 * hash) + SUPPORT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSupport()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Rate Of Change
     * timestamp : The number of milliseconds from the epoch of 1970-01-01T00:00:00Z. - When the indicator is produced
     * unit : Unit currency (Ex : BTC, ETH)
     * quote : Quote currency (Ex : EUR, USD)
     * xPeriod : Number of OHLCV used to produce the indicator
     * roc : ROC value for the period (decimal, 0.01 stands for 1%)
     * resistance : Maximal closing price in quote currency for one unit of unit currency for the period
     * support : Minimal closing price in quote currency for one unit of unit currency for the period
     * </pre>
     *
     * Protobuf type {@code colibri.ROC}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:colibri.ROC)
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROCOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_ROC_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_ROC_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC.class, io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC.Builder.class);
      }

      // Construct using io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        unit_ = 0;

        quote_ = 0;

        xPeriod_ = 0;

        roc_ = 0D;

        resistance_ = 0D;

        support_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_ROC_descriptor;
      }

      @java.lang.Override
      public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC getDefaultInstanceForType() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC.getDefaultInstance();
      }

      @java.lang.Override
      public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC build() {
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC buildPartial() {
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC result = new io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC(this);
        result.timestamp_ = timestamp_;
        result.unit_ = unit_;
        result.quote_ = quote_;
        result.xPeriod_ = xPeriod_;
        result.roc_ = roc_;
        result.resistance_ = resistance_;
        result.support_ = support_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC) {
          return mergeFrom((io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC other) {
        if (other == io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.unit_ != 0) {
          setUnitValue(other.getUnitValue());
        }
        if (other.quote_ != 0) {
          setQuoteValue(other.getQuoteValue());
        }
        if (other.getXPeriod() != 0) {
          setXPeriod(other.getXPeriod());
        }
        if (other.getRoc() != 0D) {
          setRoc(other.getRoc());
        }
        if (other.getResistance() != 0D) {
          setResistance(other.getResistance());
        }
        if (other.getSupport() != 0D) {
          setSupport(other.getSupport());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 1;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int unit_ = 0;
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @return The enum numeric value on the wire for unit.
       */
      public int getUnitValue() {
        return unit_;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @param value The enum numeric value on the wire for unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnitValue(int value) {
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @return The unit.
       */
      public io.gbdevw.colibri.domain.utils.Utils.Currency getUnit() {
        @SuppressWarnings("deprecation")
        io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(unit_);
        return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @param value The unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnit(io.gbdevw.colibri.domain.utils.Utils.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        unit_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnit() {
        
        unit_ = 0;
        onChanged();
        return this;
      }

      private int quote_ = 0;
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @return The enum numeric value on the wire for quote.
       */
      public int getQuoteValue() {
        return quote_;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @param value The enum numeric value on the wire for quote to set.
       * @return This builder for chaining.
       */
      public Builder setQuoteValue(int value) {
        quote_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @return The quote.
       */
      public io.gbdevw.colibri.domain.utils.Utils.Currency getQuote() {
        @SuppressWarnings("deprecation")
        io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(quote_);
        return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @param value The quote to set.
       * @return This builder for chaining.
       */
      public Builder setQuote(io.gbdevw.colibri.domain.utils.Utils.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        quote_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuote() {
        
        quote_ = 0;
        onChanged();
        return this;
      }

      private int xPeriod_ ;
      /**
       * <code>uint32 xPeriod = 4;</code>
       * @return The xPeriod.
       */
      public int getXPeriod() {
        return xPeriod_;
      }
      /**
       * <code>uint32 xPeriod = 4;</code>
       * @param value The xPeriod to set.
       * @return This builder for chaining.
       */
      public Builder setXPeriod(int value) {
        
        xPeriod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 xPeriod = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearXPeriod() {
        
        xPeriod_ = 0;
        onChanged();
        return this;
      }

      private double roc_ ;
      /**
       * <code>double roc = 6;</code>
       * @return The roc.
       */
      public double getRoc() {
        return roc_;
      }
      /**
       * <code>double roc = 6;</code>
       * @param value The roc to set.
       * @return This builder for chaining.
       */
      public Builder setRoc(double value) {
        
        roc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double roc = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoc() {
        
        roc_ = 0D;
        onChanged();
        return this;
      }

      private double resistance_ ;
      /**
       * <code>double resistance = 7;</code>
       * @return The resistance.
       */
      public double getResistance() {
        return resistance_;
      }
      /**
       * <code>double resistance = 7;</code>
       * @param value The resistance to set.
       * @return This builder for chaining.
       */
      public Builder setResistance(double value) {
        
        resistance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double resistance = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearResistance() {
        
        resistance_ = 0D;
        onChanged();
        return this;
      }

      private double support_ ;
      /**
       * <code>double support = 8;</code>
       * @return The support.
       */
      public double getSupport() {
        return support_;
      }
      /**
       * <code>double support = 8;</code>
       * @param value The support to set.
       * @return This builder for chaining.
       */
      public Builder setSupport(double value) {
        
        support_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double support = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearSupport() {
        
        support_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:colibri.ROC)
    }

    // @@protoc_insertion_point(class_scope:colibri.ROC)
    private static final io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC();
    }

    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ROC>
        PARSER = new com.google.protobuf.AbstractParser<ROC>() {
      @java.lang.Override
      public ROC parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ROC(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ROC> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ROC> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.ROC getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RSIOrBuilder extends
      // @@protoc_insertion_point(interface_extends:colibri.RSI)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The enum numeric value on the wire for unit.
     */
    int getUnitValue();
    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The unit.
     */
    io.gbdevw.colibri.domain.utils.Utils.Currency getUnit();

    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The enum numeric value on the wire for quote.
     */
    int getQuoteValue();
    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The quote.
     */
    io.gbdevw.colibri.domain.utils.Utils.Currency getQuote();

    /**
     * <code>uint32 xPeriod = 4;</code>
     * @return The xPeriod.
     */
    int getXPeriod();

    /**
     * <code>double rsi = 5;</code>
     * @return The rsi.
     */
    double getRsi();
  }
  /**
   * <pre>
   * Relative Strength Index
   * timestamp : The number of milliseconds from the epoch of 1970-01-01T00:00:00Z. - When the indicator is produced
   * unit : Unit currency (Ex : BTC, ETH)
   * quote : Quote currency (Ex : EUR, USD)
   * xPeriod : Number of candles used to produce the indicator
   * rsi : RSI value
   * </pre>
   *
   * Protobuf type {@code colibri.RSI}
   */
  public  static final class RSI extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:colibri.RSI)
      RSIOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RSI.newBuilder() to construct.
    private RSI(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RSI() {
      unit_ = 0;
      quote_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RSI();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RSI(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              unit_ = rawValue;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              quote_ = rawValue;
              break;
            }
            case 32: {

              xPeriod_ = input.readUInt32();
              break;
            }
            case 41: {

              rsi_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_RSI_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_RSI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI.class, io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int UNIT_FIELD_NUMBER = 2;
    private int unit_;
    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The enum numeric value on the wire for unit.
     */
    public int getUnitValue() {
      return unit_;
    }
    /**
     * <code>.colibri.Currency unit = 2;</code>
     * @return The unit.
     */
    public io.gbdevw.colibri.domain.utils.Utils.Currency getUnit() {
      @SuppressWarnings("deprecation")
      io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(unit_);
      return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
    }

    public static final int QUOTE_FIELD_NUMBER = 3;
    private int quote_;
    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The enum numeric value on the wire for quote.
     */
    public int getQuoteValue() {
      return quote_;
    }
    /**
     * <code>.colibri.Currency quote = 3;</code>
     * @return The quote.
     */
    public io.gbdevw.colibri.domain.utils.Utils.Currency getQuote() {
      @SuppressWarnings("deprecation")
      io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(quote_);
      return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
    }

    public static final int XPERIOD_FIELD_NUMBER = 4;
    private int xPeriod_;
    /**
     * <code>uint32 xPeriod = 4;</code>
     * @return The xPeriod.
     */
    public int getXPeriod() {
      return xPeriod_;
    }

    public static final int RSI_FIELD_NUMBER = 5;
    private double rsi_;
    /**
     * <code>double rsi = 5;</code>
     * @return The rsi.
     */
    public double getRsi() {
      return rsi_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeUInt64(1, timestamp_);
      }
      if (unit_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        output.writeEnum(2, unit_);
      }
      if (quote_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        output.writeEnum(3, quote_);
      }
      if (xPeriod_ != 0) {
        output.writeUInt32(4, xPeriod_);
      }
      if (rsi_ != 0D) {
        output.writeDouble(5, rsi_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      if (unit_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, unit_);
      }
      if (quote_ != io.gbdevw.colibri.domain.utils.Utils.Currency.EUR.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, quote_);
      }
      if (xPeriod_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, xPeriod_);
      }
      if (rsi_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, rsi_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI)) {
        return super.equals(obj);
      }
      io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI other = (io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI) obj;

      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (unit_ != other.unit_) return false;
      if (quote_ != other.quote_) return false;
      if (getXPeriod()
          != other.getXPeriod()) return false;
      if (java.lang.Double.doubleToLongBits(getRsi())
          != java.lang.Double.doubleToLongBits(
              other.getRsi())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + UNIT_FIELD_NUMBER;
      hash = (53 * hash) + unit_;
      hash = (37 * hash) + QUOTE_FIELD_NUMBER;
      hash = (53 * hash) + quote_;
      hash = (37 * hash) + XPERIOD_FIELD_NUMBER;
      hash = (53 * hash) + getXPeriod();
      hash = (37 * hash) + RSI_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getRsi()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Relative Strength Index
     * timestamp : The number of milliseconds from the epoch of 1970-01-01T00:00:00Z. - When the indicator is produced
     * unit : Unit currency (Ex : BTC, ETH)
     * quote : Quote currency (Ex : EUR, USD)
     * xPeriod : Number of candles used to produce the indicator
     * rsi : RSI value
     * </pre>
     *
     * Protobuf type {@code colibri.RSI}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:colibri.RSI)
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSIOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_RSI_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_RSI_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI.class, io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI.Builder.class);
      }

      // Construct using io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        unit_ = 0;

        quote_ = 0;

        xPeriod_ = 0;

        rsi_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.internal_static_colibri_RSI_descriptor;
      }

      @java.lang.Override
      public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI getDefaultInstanceForType() {
        return io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI.getDefaultInstance();
      }

      @java.lang.Override
      public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI build() {
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI buildPartial() {
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI result = new io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI(this);
        result.timestamp_ = timestamp_;
        result.unit_ = unit_;
        result.quote_ = quote_;
        result.xPeriod_ = xPeriod_;
        result.rsi_ = rsi_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI) {
          return mergeFrom((io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI other) {
        if (other == io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.unit_ != 0) {
          setUnitValue(other.getUnitValue());
        }
        if (other.quote_ != 0) {
          setQuoteValue(other.getQuoteValue());
        }
        if (other.getXPeriod() != 0) {
          setXPeriod(other.getXPeriod());
        }
        if (other.getRsi() != 0D) {
          setRsi(other.getRsi());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 1;</code>
       * @return The timestamp.
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int unit_ = 0;
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @return The enum numeric value on the wire for unit.
       */
      public int getUnitValue() {
        return unit_;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @param value The enum numeric value on the wire for unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnitValue(int value) {
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @return The unit.
       */
      public io.gbdevw.colibri.domain.utils.Utils.Currency getUnit() {
        @SuppressWarnings("deprecation")
        io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(unit_);
        return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @param value The unit to set.
       * @return This builder for chaining.
       */
      public Builder setUnit(io.gbdevw.colibri.domain.utils.Utils.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        unit_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency unit = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnit() {
        
        unit_ = 0;
        onChanged();
        return this;
      }

      private int quote_ = 0;
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @return The enum numeric value on the wire for quote.
       */
      public int getQuoteValue() {
        return quote_;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @param value The enum numeric value on the wire for quote to set.
       * @return This builder for chaining.
       */
      public Builder setQuoteValue(int value) {
        quote_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @return The quote.
       */
      public io.gbdevw.colibri.domain.utils.Utils.Currency getQuote() {
        @SuppressWarnings("deprecation")
        io.gbdevw.colibri.domain.utils.Utils.Currency result = io.gbdevw.colibri.domain.utils.Utils.Currency.valueOf(quote_);
        return result == null ? io.gbdevw.colibri.domain.utils.Utils.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @param value The quote to set.
       * @return This builder for chaining.
       */
      public Builder setQuote(io.gbdevw.colibri.domain.utils.Utils.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        quote_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.colibri.Currency quote = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuote() {
        
        quote_ = 0;
        onChanged();
        return this;
      }

      private int xPeriod_ ;
      /**
       * <code>uint32 xPeriod = 4;</code>
       * @return The xPeriod.
       */
      public int getXPeriod() {
        return xPeriod_;
      }
      /**
       * <code>uint32 xPeriod = 4;</code>
       * @param value The xPeriod to set.
       * @return This builder for chaining.
       */
      public Builder setXPeriod(int value) {
        
        xPeriod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 xPeriod = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearXPeriod() {
        
        xPeriod_ = 0;
        onChanged();
        return this;
      }

      private double rsi_ ;
      /**
       * <code>double rsi = 5;</code>
       * @return The rsi.
       */
      public double getRsi() {
        return rsi_;
      }
      /**
       * <code>double rsi = 5;</code>
       * @param value The rsi to set.
       * @return This builder for chaining.
       */
      public Builder setRsi(double value) {
        
        rsi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double rsi = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRsi() {
        
        rsi_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:colibri.RSI)
    }

    // @@protoc_insertion_point(class_scope:colibri.RSI)
    private static final io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI();
    }

    public static io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RSI>
        PARSER = new com.google.protobuf.AbstractParser<RSI>() {
      @java.lang.Override
      public RSI parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RSI(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RSI> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RSI> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.gbdevw.colibri.domain.technicalindicators.TechnicalIndicators.RSI getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_colibri_MACD_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_colibri_MACD_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_colibri_ROC_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_colibri_ROC_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_colibri_RSI_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_colibri_RSI_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031TechnicalIndicators.proto\022\007colibri\032\013Ut" +
      "ils.proto\"z\n\004MACD\022\021\n\ttimestamp\030\001 \001(\004\022\037\n\004" +
      "unit\030\002 \001(\0162\021.colibri.Currency\022 \n\005quote\030\003" +
      " \001(\0162\021.colibri.Currency\022\014\n\004macd\030\004 \001(\001\022\016\n" +
      "\006signal\030\005 \001(\001\"\236\001\n\003ROC\022\021\n\ttimestamp\030\001 \001(\004" +
      "\022\037\n\004unit\030\002 \001(\0162\021.colibri.Currency\022 \n\005quo" +
      "te\030\003 \001(\0162\021.colibri.Currency\022\017\n\007xPeriod\030\004" +
      " \001(\r\022\013\n\003roc\030\006 \001(\001\022\022\n\nresistance\030\007 \001(\001\022\017\n" +
      "\007support\030\010 \001(\001\"y\n\003RSI\022\021\n\ttimestamp\030\001 \001(\004" +
      "\022\037\n\004unit\030\002 \001(\0162\021.colibri.Currency\022 \n\005quo" +
      "te\030\003 \001(\0162\021.colibri.Currency\022\017\n\007xPeriod\030\004" +
      " \001(\r\022\013\n\003rsi\030\005 \001(\001B.\n,io.gbdevw.colibri.d" +
      "omain.technicalindicatorsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.gbdevw.colibri.domain.utils.Utils.getDescriptor(),
        });
    internal_static_colibri_MACD_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_colibri_MACD_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_colibri_MACD_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "Macd", "Signal", });
    internal_static_colibri_ROC_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_colibri_ROC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_colibri_ROC_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "XPeriod", "Roc", "Resistance", "Support", });
    internal_static_colibri_RSI_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_colibri_RSI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_colibri_RSI_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "XPeriod", "Rsi", });
    io.gbdevw.colibri.domain.utils.Utils.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
