// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package tech.gbdevw.colibri.domain;

/**
 * <pre>
 * Bolinger Bands
 * timestamp : The number of milliseconds from the epoch of 1970-01-01T00:00:00Z. - When the indicator is produced
 * unit : Unit Currency (Ex : BTC, ETH)
 * quote : Quote Currency (Ex : EUR, USD)
 * xPeriod : Number of periods used to compute the indicator
 * bolu1 : Upper Bolinger band for 1 standard deviation
 * bolu2 : Upper Bolinger band for 2 standard deviations
 * bolu3 : Upper Bolinger band for 3 standard deviations
 * bolu4 : Upper Bolinger band for 4 standard deviations  
 * bold1 : Lower Bolinger band for 1 standard deviation
 * bold2 : Lower Bolinger band for 2 standard deviations
 * bold3 : Lower Bolinger band for 3 standard deviations
 * bold4 : Lower Bolinger band for 4 standard deviations  
 * </pre>
 *
 * Protobuf type {@code tech.gbdevw.colibri.domain.BOL}
 */
public  final class BOL extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tech.gbdevw.colibri.domain.BOL)
    BOLOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BOL.newBuilder() to construct.
  private BOL(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BOL() {
    unit_ = 0;
    quote_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new BOL();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BOL(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            timestamp_ = input.readUInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            unit_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            quote_ = rawValue;
            break;
          }
          case 32: {

            xPeriod_ = input.readUInt32();
            break;
          }
          case 41: {

            bolu1_ = input.readDouble();
            break;
          }
          case 49: {

            bolu2_ = input.readDouble();
            break;
          }
          case 57: {

            bolu3_ = input.readDouble();
            break;
          }
          case 65: {

            bolu4_ = input.readDouble();
            break;
          }
          case 73: {

            bold1_ = input.readDouble();
            break;
          }
          case 81: {

            bold2_ = input.readDouble();
            break;
          }
          case 89: {

            bold3_ = input.readDouble();
            break;
          }
          case 97: {

            bold4_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return tech.gbdevw.colibri.domain.Domain.internal_static_tech_gbdevw_colibri_domain_BOL_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return tech.gbdevw.colibri.domain.Domain.internal_static_tech_gbdevw_colibri_domain_BOL_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            tech.gbdevw.colibri.domain.BOL.class, tech.gbdevw.colibri.domain.BOL.Builder.class);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 1;</code>
   * @return The timestamp.
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int UNIT_FIELD_NUMBER = 2;
  private int unit_;
  /**
   * <code>.tech.gbdevw.colibri.domain.Currency unit = 2;</code>
   * @return The enum numeric value on the wire for unit.
   */
  public int getUnitValue() {
    return unit_;
  }
  /**
   * <code>.tech.gbdevw.colibri.domain.Currency unit = 2;</code>
   * @return The unit.
   */
  public tech.gbdevw.colibri.domain.Currency getUnit() {
    @SuppressWarnings("deprecation")
    tech.gbdevw.colibri.domain.Currency result = tech.gbdevw.colibri.domain.Currency.valueOf(unit_);
    return result == null ? tech.gbdevw.colibri.domain.Currency.UNRECOGNIZED : result;
  }

  public static final int QUOTE_FIELD_NUMBER = 3;
  private int quote_;
  /**
   * <code>.tech.gbdevw.colibri.domain.Currency quote = 3;</code>
   * @return The enum numeric value on the wire for quote.
   */
  public int getQuoteValue() {
    return quote_;
  }
  /**
   * <code>.tech.gbdevw.colibri.domain.Currency quote = 3;</code>
   * @return The quote.
   */
  public tech.gbdevw.colibri.domain.Currency getQuote() {
    @SuppressWarnings("deprecation")
    tech.gbdevw.colibri.domain.Currency result = tech.gbdevw.colibri.domain.Currency.valueOf(quote_);
    return result == null ? tech.gbdevw.colibri.domain.Currency.UNRECOGNIZED : result;
  }

  public static final int XPERIOD_FIELD_NUMBER = 4;
  private int xPeriod_;
  /**
   * <code>uint32 xPeriod = 4;</code>
   * @return The xPeriod.
   */
  public int getXPeriod() {
    return xPeriod_;
  }

  public static final int BOLU1_FIELD_NUMBER = 5;
  private double bolu1_;
  /**
   * <code>double bolu1 = 5;</code>
   * @return The bolu1.
   */
  public double getBolu1() {
    return bolu1_;
  }

  public static final int BOLU2_FIELD_NUMBER = 6;
  private double bolu2_;
  /**
   * <code>double bolu2 = 6;</code>
   * @return The bolu2.
   */
  public double getBolu2() {
    return bolu2_;
  }

  public static final int BOLU3_FIELD_NUMBER = 7;
  private double bolu3_;
  /**
   * <code>double bolu3 = 7;</code>
   * @return The bolu3.
   */
  public double getBolu3() {
    return bolu3_;
  }

  public static final int BOLU4_FIELD_NUMBER = 8;
  private double bolu4_;
  /**
   * <code>double bolu4 = 8;</code>
   * @return The bolu4.
   */
  public double getBolu4() {
    return bolu4_;
  }

  public static final int BOLD1_FIELD_NUMBER = 9;
  private double bold1_;
  /**
   * <code>double bold1 = 9;</code>
   * @return The bold1.
   */
  public double getBold1() {
    return bold1_;
  }

  public static final int BOLD2_FIELD_NUMBER = 10;
  private double bold2_;
  /**
   * <code>double bold2 = 10;</code>
   * @return The bold2.
   */
  public double getBold2() {
    return bold2_;
  }

  public static final int BOLD3_FIELD_NUMBER = 11;
  private double bold3_;
  /**
   * <code>double bold3 = 11;</code>
   * @return The bold3.
   */
  public double getBold3() {
    return bold3_;
  }

  public static final int BOLD4_FIELD_NUMBER = 12;
  private double bold4_;
  /**
   * <code>double bold4 = 12;</code>
   * @return The bold4.
   */
  public double getBold4() {
    return bold4_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != 0L) {
      output.writeUInt64(1, timestamp_);
    }
    if (unit_ != tech.gbdevw.colibri.domain.Currency.EUR.getNumber()) {
      output.writeEnum(2, unit_);
    }
    if (quote_ != tech.gbdevw.colibri.domain.Currency.EUR.getNumber()) {
      output.writeEnum(3, quote_);
    }
    if (xPeriod_ != 0) {
      output.writeUInt32(4, xPeriod_);
    }
    if (bolu1_ != 0D) {
      output.writeDouble(5, bolu1_);
    }
    if (bolu2_ != 0D) {
      output.writeDouble(6, bolu2_);
    }
    if (bolu3_ != 0D) {
      output.writeDouble(7, bolu3_);
    }
    if (bolu4_ != 0D) {
      output.writeDouble(8, bolu4_);
    }
    if (bold1_ != 0D) {
      output.writeDouble(9, bold1_);
    }
    if (bold2_ != 0D) {
      output.writeDouble(10, bold2_);
    }
    if (bold3_ != 0D) {
      output.writeDouble(11, bold3_);
    }
    if (bold4_ != 0D) {
      output.writeDouble(12, bold4_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, timestamp_);
    }
    if (unit_ != tech.gbdevw.colibri.domain.Currency.EUR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, unit_);
    }
    if (quote_ != tech.gbdevw.colibri.domain.Currency.EUR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, quote_);
    }
    if (xPeriod_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, xPeriod_);
    }
    if (bolu1_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, bolu1_);
    }
    if (bolu2_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, bolu2_);
    }
    if (bolu3_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, bolu3_);
    }
    if (bolu4_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, bolu4_);
    }
    if (bold1_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, bold1_);
    }
    if (bold2_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(10, bold2_);
    }
    if (bold3_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, bold3_);
    }
    if (bold4_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(12, bold4_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof tech.gbdevw.colibri.domain.BOL)) {
      return super.equals(obj);
    }
    tech.gbdevw.colibri.domain.BOL other = (tech.gbdevw.colibri.domain.BOL) obj;

    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (unit_ != other.unit_) return false;
    if (quote_ != other.quote_) return false;
    if (getXPeriod()
        != other.getXPeriod()) return false;
    if (java.lang.Double.doubleToLongBits(getBolu1())
        != java.lang.Double.doubleToLongBits(
            other.getBolu1())) return false;
    if (java.lang.Double.doubleToLongBits(getBolu2())
        != java.lang.Double.doubleToLongBits(
            other.getBolu2())) return false;
    if (java.lang.Double.doubleToLongBits(getBolu3())
        != java.lang.Double.doubleToLongBits(
            other.getBolu3())) return false;
    if (java.lang.Double.doubleToLongBits(getBolu4())
        != java.lang.Double.doubleToLongBits(
            other.getBolu4())) return false;
    if (java.lang.Double.doubleToLongBits(getBold1())
        != java.lang.Double.doubleToLongBits(
            other.getBold1())) return false;
    if (java.lang.Double.doubleToLongBits(getBold2())
        != java.lang.Double.doubleToLongBits(
            other.getBold2())) return false;
    if (java.lang.Double.doubleToLongBits(getBold3())
        != java.lang.Double.doubleToLongBits(
            other.getBold3())) return false;
    if (java.lang.Double.doubleToLongBits(getBold4())
        != java.lang.Double.doubleToLongBits(
            other.getBold4())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + UNIT_FIELD_NUMBER;
    hash = (53 * hash) + unit_;
    hash = (37 * hash) + QUOTE_FIELD_NUMBER;
    hash = (53 * hash) + quote_;
    hash = (37 * hash) + XPERIOD_FIELD_NUMBER;
    hash = (53 * hash) + getXPeriod();
    hash = (37 * hash) + BOLU1_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBolu1()));
    hash = (37 * hash) + BOLU2_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBolu2()));
    hash = (37 * hash) + BOLU3_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBolu3()));
    hash = (37 * hash) + BOLU4_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBolu4()));
    hash = (37 * hash) + BOLD1_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBold1()));
    hash = (37 * hash) + BOLD2_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBold2()));
    hash = (37 * hash) + BOLD3_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBold3()));
    hash = (37 * hash) + BOLD4_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBold4()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static tech.gbdevw.colibri.domain.BOL parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.gbdevw.colibri.domain.BOL parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.gbdevw.colibri.domain.BOL parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.gbdevw.colibri.domain.BOL parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.gbdevw.colibri.domain.BOL parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static tech.gbdevw.colibri.domain.BOL parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static tech.gbdevw.colibri.domain.BOL parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.gbdevw.colibri.domain.BOL parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.gbdevw.colibri.domain.BOL parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static tech.gbdevw.colibri.domain.BOL parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static tech.gbdevw.colibri.domain.BOL parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static tech.gbdevw.colibri.domain.BOL parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(tech.gbdevw.colibri.domain.BOL prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Bolinger Bands
   * timestamp : The number of milliseconds from the epoch of 1970-01-01T00:00:00Z. - When the indicator is produced
   * unit : Unit Currency (Ex : BTC, ETH)
   * quote : Quote Currency (Ex : EUR, USD)
   * xPeriod : Number of periods used to compute the indicator
   * bolu1 : Upper Bolinger band for 1 standard deviation
   * bolu2 : Upper Bolinger band for 2 standard deviations
   * bolu3 : Upper Bolinger band for 3 standard deviations
   * bolu4 : Upper Bolinger band for 4 standard deviations  
   * bold1 : Lower Bolinger band for 1 standard deviation
   * bold2 : Lower Bolinger band for 2 standard deviations
   * bold3 : Lower Bolinger band for 3 standard deviations
   * bold4 : Lower Bolinger band for 4 standard deviations  
   * </pre>
   *
   * Protobuf type {@code tech.gbdevw.colibri.domain.BOL}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tech.gbdevw.colibri.domain.BOL)
      tech.gbdevw.colibri.domain.BOLOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tech.gbdevw.colibri.domain.Domain.internal_static_tech_gbdevw_colibri_domain_BOL_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tech.gbdevw.colibri.domain.Domain.internal_static_tech_gbdevw_colibri_domain_BOL_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tech.gbdevw.colibri.domain.BOL.class, tech.gbdevw.colibri.domain.BOL.Builder.class);
    }

    // Construct using tech.gbdevw.colibri.domain.BOL.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timestamp_ = 0L;

      unit_ = 0;

      quote_ = 0;

      xPeriod_ = 0;

      bolu1_ = 0D;

      bolu2_ = 0D;

      bolu3_ = 0D;

      bolu4_ = 0D;

      bold1_ = 0D;

      bold2_ = 0D;

      bold3_ = 0D;

      bold4_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return tech.gbdevw.colibri.domain.Domain.internal_static_tech_gbdevw_colibri_domain_BOL_descriptor;
    }

    @java.lang.Override
    public tech.gbdevw.colibri.domain.BOL getDefaultInstanceForType() {
      return tech.gbdevw.colibri.domain.BOL.getDefaultInstance();
    }

    @java.lang.Override
    public tech.gbdevw.colibri.domain.BOL build() {
      tech.gbdevw.colibri.domain.BOL result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public tech.gbdevw.colibri.domain.BOL buildPartial() {
      tech.gbdevw.colibri.domain.BOL result = new tech.gbdevw.colibri.domain.BOL(this);
      result.timestamp_ = timestamp_;
      result.unit_ = unit_;
      result.quote_ = quote_;
      result.xPeriod_ = xPeriod_;
      result.bolu1_ = bolu1_;
      result.bolu2_ = bolu2_;
      result.bolu3_ = bolu3_;
      result.bolu4_ = bolu4_;
      result.bold1_ = bold1_;
      result.bold2_ = bold2_;
      result.bold3_ = bold3_;
      result.bold4_ = bold4_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof tech.gbdevw.colibri.domain.BOL) {
        return mergeFrom((tech.gbdevw.colibri.domain.BOL)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(tech.gbdevw.colibri.domain.BOL other) {
      if (other == tech.gbdevw.colibri.domain.BOL.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.unit_ != 0) {
        setUnitValue(other.getUnitValue());
      }
      if (other.quote_ != 0) {
        setQuoteValue(other.getQuoteValue());
      }
      if (other.getXPeriod() != 0) {
        setXPeriod(other.getXPeriod());
      }
      if (other.getBolu1() != 0D) {
        setBolu1(other.getBolu1());
      }
      if (other.getBolu2() != 0D) {
        setBolu2(other.getBolu2());
      }
      if (other.getBolu3() != 0D) {
        setBolu3(other.getBolu3());
      }
      if (other.getBolu4() != 0D) {
        setBolu4(other.getBolu4());
      }
      if (other.getBold1() != 0D) {
        setBold1(other.getBold1());
      }
      if (other.getBold2() != 0D) {
        setBold2(other.getBold2());
      }
      if (other.getBold3() != 0D) {
        setBold3(other.getBold3());
      }
      if (other.getBold4() != 0D) {
        setBold4(other.getBold4());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      tech.gbdevw.colibri.domain.BOL parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (tech.gbdevw.colibri.domain.BOL) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint64 timestamp = 1;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private int unit_ = 0;
    /**
     * <code>.tech.gbdevw.colibri.domain.Currency unit = 2;</code>
     * @return The enum numeric value on the wire for unit.
     */
    public int getUnitValue() {
      return unit_;
    }
    /**
     * <code>.tech.gbdevw.colibri.domain.Currency unit = 2;</code>
     * @param value The enum numeric value on the wire for unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnitValue(int value) {
      unit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.tech.gbdevw.colibri.domain.Currency unit = 2;</code>
     * @return The unit.
     */
    public tech.gbdevw.colibri.domain.Currency getUnit() {
      @SuppressWarnings("deprecation")
      tech.gbdevw.colibri.domain.Currency result = tech.gbdevw.colibri.domain.Currency.valueOf(unit_);
      return result == null ? tech.gbdevw.colibri.domain.Currency.UNRECOGNIZED : result;
    }
    /**
     * <code>.tech.gbdevw.colibri.domain.Currency unit = 2;</code>
     * @param value The unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnit(tech.gbdevw.colibri.domain.Currency value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      unit_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.tech.gbdevw.colibri.domain.Currency unit = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnit() {
      
      unit_ = 0;
      onChanged();
      return this;
    }

    private int quote_ = 0;
    /**
     * <code>.tech.gbdevw.colibri.domain.Currency quote = 3;</code>
     * @return The enum numeric value on the wire for quote.
     */
    public int getQuoteValue() {
      return quote_;
    }
    /**
     * <code>.tech.gbdevw.colibri.domain.Currency quote = 3;</code>
     * @param value The enum numeric value on the wire for quote to set.
     * @return This builder for chaining.
     */
    public Builder setQuoteValue(int value) {
      quote_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.tech.gbdevw.colibri.domain.Currency quote = 3;</code>
     * @return The quote.
     */
    public tech.gbdevw.colibri.domain.Currency getQuote() {
      @SuppressWarnings("deprecation")
      tech.gbdevw.colibri.domain.Currency result = tech.gbdevw.colibri.domain.Currency.valueOf(quote_);
      return result == null ? tech.gbdevw.colibri.domain.Currency.UNRECOGNIZED : result;
    }
    /**
     * <code>.tech.gbdevw.colibri.domain.Currency quote = 3;</code>
     * @param value The quote to set.
     * @return This builder for chaining.
     */
    public Builder setQuote(tech.gbdevw.colibri.domain.Currency value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      quote_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.tech.gbdevw.colibri.domain.Currency quote = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuote() {
      
      quote_ = 0;
      onChanged();
      return this;
    }

    private int xPeriod_ ;
    /**
     * <code>uint32 xPeriod = 4;</code>
     * @return The xPeriod.
     */
    public int getXPeriod() {
      return xPeriod_;
    }
    /**
     * <code>uint32 xPeriod = 4;</code>
     * @param value The xPeriod to set.
     * @return This builder for chaining.
     */
    public Builder setXPeriod(int value) {
      
      xPeriod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 xPeriod = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearXPeriod() {
      
      xPeriod_ = 0;
      onChanged();
      return this;
    }

    private double bolu1_ ;
    /**
     * <code>double bolu1 = 5;</code>
     * @return The bolu1.
     */
    public double getBolu1() {
      return bolu1_;
    }
    /**
     * <code>double bolu1 = 5;</code>
     * @param value The bolu1 to set.
     * @return This builder for chaining.
     */
    public Builder setBolu1(double value) {
      
      bolu1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bolu1 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearBolu1() {
      
      bolu1_ = 0D;
      onChanged();
      return this;
    }

    private double bolu2_ ;
    /**
     * <code>double bolu2 = 6;</code>
     * @return The bolu2.
     */
    public double getBolu2() {
      return bolu2_;
    }
    /**
     * <code>double bolu2 = 6;</code>
     * @param value The bolu2 to set.
     * @return This builder for chaining.
     */
    public Builder setBolu2(double value) {
      
      bolu2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bolu2 = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBolu2() {
      
      bolu2_ = 0D;
      onChanged();
      return this;
    }

    private double bolu3_ ;
    /**
     * <code>double bolu3 = 7;</code>
     * @return The bolu3.
     */
    public double getBolu3() {
      return bolu3_;
    }
    /**
     * <code>double bolu3 = 7;</code>
     * @param value The bolu3 to set.
     * @return This builder for chaining.
     */
    public Builder setBolu3(double value) {
      
      bolu3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bolu3 = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearBolu3() {
      
      bolu3_ = 0D;
      onChanged();
      return this;
    }

    private double bolu4_ ;
    /**
     * <code>double bolu4 = 8;</code>
     * @return The bolu4.
     */
    public double getBolu4() {
      return bolu4_;
    }
    /**
     * <code>double bolu4 = 8;</code>
     * @param value The bolu4 to set.
     * @return This builder for chaining.
     */
    public Builder setBolu4(double value) {
      
      bolu4_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bolu4 = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearBolu4() {
      
      bolu4_ = 0D;
      onChanged();
      return this;
    }

    private double bold1_ ;
    /**
     * <code>double bold1 = 9;</code>
     * @return The bold1.
     */
    public double getBold1() {
      return bold1_;
    }
    /**
     * <code>double bold1 = 9;</code>
     * @param value The bold1 to set.
     * @return This builder for chaining.
     */
    public Builder setBold1(double value) {
      
      bold1_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bold1 = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearBold1() {
      
      bold1_ = 0D;
      onChanged();
      return this;
    }

    private double bold2_ ;
    /**
     * <code>double bold2 = 10;</code>
     * @return The bold2.
     */
    public double getBold2() {
      return bold2_;
    }
    /**
     * <code>double bold2 = 10;</code>
     * @param value The bold2 to set.
     * @return This builder for chaining.
     */
    public Builder setBold2(double value) {
      
      bold2_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bold2 = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBold2() {
      
      bold2_ = 0D;
      onChanged();
      return this;
    }

    private double bold3_ ;
    /**
     * <code>double bold3 = 11;</code>
     * @return The bold3.
     */
    public double getBold3() {
      return bold3_;
    }
    /**
     * <code>double bold3 = 11;</code>
     * @param value The bold3 to set.
     * @return This builder for chaining.
     */
    public Builder setBold3(double value) {
      
      bold3_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bold3 = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearBold3() {
      
      bold3_ = 0D;
      onChanged();
      return this;
    }

    private double bold4_ ;
    /**
     * <code>double bold4 = 12;</code>
     * @return The bold4.
     */
    public double getBold4() {
      return bold4_;
    }
    /**
     * <code>double bold4 = 12;</code>
     * @param value The bold4 to set.
     * @return This builder for chaining.
     */
    public Builder setBold4(double value) {
      
      bold4_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double bold4 = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearBold4() {
      
      bold4_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tech.gbdevw.colibri.domain.BOL)
  }

  // @@protoc_insertion_point(class_scope:tech.gbdevw.colibri.domain.BOL)
  private static final tech.gbdevw.colibri.domain.BOL DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new tech.gbdevw.colibri.domain.BOL();
  }

  public static tech.gbdevw.colibri.domain.BOL getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BOL>
      PARSER = new com.google.protobuf.AbstractParser<BOL>() {
    @java.lang.Override
    public BOL parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BOL(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BOL> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BOL> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public tech.gbdevw.colibri.domain.BOL getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

