// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package tech.gbdevw.colibri.domain;

public final class Domain {
  private Domain() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tech_gbdevw_colibri_domain_Match_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tech_gbdevw_colibri_domain_Match_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tech_gbdevw_colibri_domain_Ticker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tech_gbdevw_colibri_domain_Ticker_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tech_gbdevw_colibri_domain_OHLCV_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tech_gbdevw_colibri_domain_OHLCV_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tech_gbdevw_colibri_domain_SMA_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tech_gbdevw_colibri_domain_SMA_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tech_gbdevw_colibri_domain_EMA_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tech_gbdevw_colibri_domain_EMA_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tech_gbdevw_colibri_domain_MACD_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tech_gbdevw_colibri_domain_MACD_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tech_gbdevw_colibri_domain_KLO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tech_gbdevw_colibri_domain_KLO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tech_gbdevw_colibri_domain_ROC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tech_gbdevw_colibri_domain_ROC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tech_gbdevw_colibri_domain_RSI_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tech_gbdevw_colibri_domain_RSI_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tech_gbdevw_colibri_domain_MFI_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tech_gbdevw_colibri_domain_MFI_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tech_gbdevw_colibri_domain_BOL_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tech_gbdevw_colibri_domain_BOL_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014domain.proto\022\032tech.gbdevw.colibri.doma" +
      "in\"\334\001\n\005Match\022\021\n\ttimestamp\030\001 \001(\004\022\n\n\002id\030\002 " +
      "\001(\004\0222\n\004unit\030\003 \001(\0162$.tech.gbdevw.colibri." +
      "domain.Currency\0223\n\005quote\030\004 \001(\0162$.tech.gb" +
      "devw.colibri.domain.Currency\022\r\n\005price\030\005 " +
      "\001(\001\022\014\n\004size\030\006 \001(\001\022.\n\004side\030\007 \001(\0162 .tech.g" +
      "bdevw.colibri.domain.Side\"\232\002\n\006Ticker\022\021\n\t" +
      "timestamp\030\001 \001(\004\022\n\n\002id\030\002 \001(\004\0222\n\004unit\030\003 \001(" +
      "\0162$.tech.gbdevw.colibri.domain.Currency\022" +
      "3\n\005quote\030\004 \001(\0162$.tech.gbdevw.colibri.dom" +
      "ain.Currency\022\026\n\016lastTradePrice\030\005 \001(\001\022\025\n\r" +
      "lastTradeSize\030\006 \001(\001\0227\n\rlastTradeSide\030\007 \001" +
      "(\0162 .tech.gbdevw.colibri.domain.Side\022\017\n\007" +
      "bestBid\030\010 \001(\001\022\017\n\007bestAsk\030\t \001(\001\"\366\001\n\005OHLCV" +
      "\022\023\n\013periodStart\030\001 \001(\004\0222\n\004unit\030\002 \001(\0162$.te" +
      "ch.gbdevw.colibri.domain.Currency\0223\n\005quo" +
      "te\030\003 \001(\0162$.tech.gbdevw.colibri.domain.Cu" +
      "rrency\022\017\n\007xPeriod\030\004 \001(\004\022\026\n\016periodDuratio" +
      "n\030\005 \001(\004\022\014\n\004open\030\006 \001(\001\022\014\n\004high\030\007 \001(\001\022\013\n\003l" +
      "ow\030\010 \001(\001\022\r\n\005close\030\t \001(\001\022\016\n\006volume\030\n \001(\001\"" +
      "\220\001\n\003SMA\022\021\n\ttimestamp\030\001 \001(\004\0222\n\004unit\030\002 \001(\016" +
      "2$.tech.gbdevw.colibri.domain.Currency\0223" +
      "\n\005quote\030\003 \001(\0162$.tech.gbdevw.colibri.doma" +
      "in.Currency\022\r\n\005value\030\004 \001(\001\"\220\001\n\003EMA\022\021\n\tti" +
      "mestamp\030\001 \001(\004\0222\n\004unit\030\002 \001(\0162$.tech.gbdev" +
      "w.colibri.domain.Currency\0223\n\005quote\030\003 \001(\016" +
      "2$.tech.gbdevw.colibri.domain.Currency\022\r" +
      "\n\005value\030\004 \001(\001\"\240\001\n\004MACD\022\021\n\ttimestamp\030\001 \001(" +
      "\004\0222\n\004unit\030\002 \001(\0162$.tech.gbdevw.colibri.do" +
      "main.Currency\0223\n\005quote\030\003 \001(\0162$.tech.gbde" +
      "vw.colibri.domain.Currency\022\014\n\004macd\030\004 \001(\001" +
      "\022\016\n\006signal\030\005 \001(\001\"\236\001\n\003KLO\022\021\n\ttimestamp\030\001 " +
      "\001(\004\0222\n\004unit\030\002 \001(\0162$.tech.gbdevw.colibri." +
      "domain.Currency\0223\n\005quote\030\003 \001(\0162$.tech.gb" +
      "devw.colibri.domain.Currency\022\013\n\003klo\030\004 \001(" +
      "\001\022\016\n\006signal\030\005 \001(\001\"\304\001\n\003ROC\022\021\n\ttimestamp\030\001" +
      " \001(\004\0222\n\004unit\030\002 \001(\0162$.tech.gbdevw.colibri" +
      ".domain.Currency\0223\n\005quote\030\003 \001(\0162$.tech.g" +
      "bdevw.colibri.domain.Currency\022\017\n\007xPeriod" +
      "\030\004 \001(\r\022\013\n\003roc\030\006 \001(\001\022\022\n\nresistance\030\007 \001(\001\022" +
      "\017\n\007support\030\010 \001(\001\"\216\001\n\003RSI\022\021\n\ttimestamp\030\001 " +
      "\001(\004\0222\n\004unit\030\002 \001(\0162$.tech.gbdevw.colibri." +
      "domain.Currency\0223\n\005quote\030\003 \001(\0162$.tech.gb" +
      "devw.colibri.domain.Currency\022\013\n\003rsi\030\004 \001(" +
      "\001\"\216\001\n\003MFI\022\021\n\ttimestamp\030\001 \001(\004\0222\n\004unit\030\002 \001" +
      "(\0162$.tech.gbdevw.colibri.domain.Currency" +
      "\0223\n\005quote\030\003 \001(\0162$.tech.gbdevw.colibri.do" +
      "main.Currency\022\013\n\003mfi\030\004 \001(\001\"\275\001\n\003BOL\022\021\n\tti" +
      "mestamp\030\001 \001(\004\0222\n\004unit\030\002 \001(\0162$.tech.gbdev" +
      "w.colibri.domain.Currency\0223\n\005quote\030\003 \001(\016" +
      "2$.tech.gbdevw.colibri.domain.Currency\022\r" +
      "\n\005bolu1\030\004 \001(\001\022\r\n\005bolu2\030\005 \001(\001\022\r\n\005bold1\030\006 " +
      "\001(\001\022\r\n\005bold2\030\007 \001(\001*.\n\010Currency\022\007\n\003EUR\020\000\022" +
      "\007\n\003USD\020\001\022\007\n\003BTC\020\002\022\007\n\003ETH\020\003*\031\n\004Side\022\007\n\003BU" +
      "Y\020\000\022\010\n\004SELL\020\001B\036\n\032tech.gbdevw.colibri.dom" +
      "ainP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_tech_gbdevw_colibri_domain_Match_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tech_gbdevw_colibri_domain_Match_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tech_gbdevw_colibri_domain_Match_descriptor,
        new java.lang.String[] { "Timestamp", "Id", "Unit", "Quote", "Price", "Size", "Side", });
    internal_static_tech_gbdevw_colibri_domain_Ticker_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tech_gbdevw_colibri_domain_Ticker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tech_gbdevw_colibri_domain_Ticker_descriptor,
        new java.lang.String[] { "Timestamp", "Id", "Unit", "Quote", "LastTradePrice", "LastTradeSize", "LastTradeSide", "BestBid", "BestAsk", });
    internal_static_tech_gbdevw_colibri_domain_OHLCV_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tech_gbdevw_colibri_domain_OHLCV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tech_gbdevw_colibri_domain_OHLCV_descriptor,
        new java.lang.String[] { "PeriodStart", "Unit", "Quote", "XPeriod", "PeriodDuration", "Open", "High", "Low", "Close", "Volume", });
    internal_static_tech_gbdevw_colibri_domain_SMA_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tech_gbdevw_colibri_domain_SMA_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tech_gbdevw_colibri_domain_SMA_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "Value", });
    internal_static_tech_gbdevw_colibri_domain_EMA_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tech_gbdevw_colibri_domain_EMA_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tech_gbdevw_colibri_domain_EMA_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "Value", });
    internal_static_tech_gbdevw_colibri_domain_MACD_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tech_gbdevw_colibri_domain_MACD_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tech_gbdevw_colibri_domain_MACD_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "Macd", "Signal", });
    internal_static_tech_gbdevw_colibri_domain_KLO_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tech_gbdevw_colibri_domain_KLO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tech_gbdevw_colibri_domain_KLO_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "Klo", "Signal", });
    internal_static_tech_gbdevw_colibri_domain_ROC_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tech_gbdevw_colibri_domain_ROC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tech_gbdevw_colibri_domain_ROC_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "XPeriod", "Roc", "Resistance", "Support", });
    internal_static_tech_gbdevw_colibri_domain_RSI_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_tech_gbdevw_colibri_domain_RSI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tech_gbdevw_colibri_domain_RSI_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "Rsi", });
    internal_static_tech_gbdevw_colibri_domain_MFI_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_tech_gbdevw_colibri_domain_MFI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tech_gbdevw_colibri_domain_MFI_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "Mfi", });
    internal_static_tech_gbdevw_colibri_domain_BOL_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_tech_gbdevw_colibri_domain_BOL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tech_gbdevw_colibri_domain_BOL_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "Bolu1", "Bolu2", "Bold1", "Bold2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
