on:
  push:
    branches:
      - master
jobs:
  build_test_deploy:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build, Test & Deploy with Maven
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
