// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package gbdevw.colibri.domain;

public final class Domain {
  private Domain() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gbdevw_colibri_domain_Match_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gbdevw_colibri_domain_Match_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gbdevw_colibri_domain_Ticker_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gbdevw_colibri_domain_Ticker_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gbdevw_colibri_domain_OHLCV_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gbdevw_colibri_domain_OHLCV_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gbdevw_colibri_domain_MACD_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gbdevw_colibri_domain_MACD_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gbdevw_colibri_domain_ROC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gbdevw_colibri_domain_ROC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gbdevw_colibri_domain_RSI_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gbdevw_colibri_domain_RSI_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014domain.proto\022\025gbdevw.colibri.domain\"\315\001" +
      "\n\005Match\022\021\n\ttimestamp\030\001 \001(\004\022\n\n\002id\030\002 \001(\004\022-" +
      "\n\004unit\030\003 \001(\0162\037.gbdevw.colibri.domain.Cur" +
      "rency\022.\n\005quote\030\004 \001(\0162\037.gbdevw.colibri.do" +
      "main.Currency\022\r\n\005price\030\005 \001(\001\022\014\n\004size\030\006 \001" +
      "(\001\022)\n\004Side\030\007 \001(\0162\033.gbdevw.colibri.domain" +
      ".Side\"\213\002\n\006Ticker\022\021\n\ttimestamp\030\001 \001(\004\022\n\n\002i" +
      "d\030\002 \001(\004\022-\n\004unit\030\003 \001(\0162\037.gbdevw.colibri.d" +
      "omain.Currency\022.\n\005quote\030\004 \001(\0162\037.gbdevw.c" +
      "olibri.domain.Currency\022\026\n\016lastTradePrice" +
      "\030\005 \001(\001\022\025\n\rlastTradeSize\030\006 \001(\001\0222\n\rlastTra" +
      "deSide\030\007 \001(\0162\033.gbdevw.colibri.domain.Sid" +
      "e\022\017\n\007bestBid\030\010 \001(\001\022\017\n\007bestAsk\030\t \001(\001\"\333\001\n\005" +
      "OHLCV\022\023\n\013periodStart\030\001 \001(\004\022-\n\004unit\030\002 \001(\016" +
      "2\037.gbdevw.colibri.domain.Currency\022.\n\005quo" +
      "te\030\003 \001(\0162\037.gbdevw.colibri.domain.Currenc" +
      "y\022\026\n\016periodDuration\030\004 \001(\004\022\014\n\004open\030\005 \001(\001\022" +
      "\014\n\004high\030\006 \001(\001\022\013\n\003low\030\007 \001(\001\022\r\n\005close\030\010 \001(" +
      "\001\022\016\n\006volume\030\t \001(\001\"\226\001\n\004MACD\022\021\n\ttimestamp\030" +
      "\001 \001(\004\022-\n\004unit\030\002 \001(\0162\037.gbdevw.colibri.dom" +
      "ain.Currency\022.\n\005quote\030\003 \001(\0162\037.gbdevw.col" +
      "ibri.domain.Currency\022\014\n\004macd\030\004 \001(\001\022\016\n\006si" +
      "gnal\030\005 \001(\001\"\272\001\n\003ROC\022\021\n\ttimestamp\030\001 \001(\004\022-\n" +
      "\004unit\030\002 \001(\0162\037.gbdevw.colibri.domain.Curr" +
      "ency\022.\n\005quote\030\003 \001(\0162\037.gbdevw.colibri.dom" +
      "ain.Currency\022\017\n\007xPeriod\030\004 \001(\r\022\013\n\003roc\030\006 \001" +
      "(\001\022\022\n\nresistance\030\007 \001(\001\022\017\n\007support\030\010 \001(\001\"" +
      "\225\001\n\003RSI\022\021\n\ttimestamp\030\001 \001(\004\022-\n\004unit\030\002 \001(\016" +
      "2\037.gbdevw.colibri.domain.Currency\022.\n\005quo" +
      "te\030\003 \001(\0162\037.gbdevw.colibri.domain.Currenc" +
      "y\022\017\n\007xPeriod\030\004 \001(\r\022\013\n\003rsi\030\005 \001(\001*.\n\010Curre" +
      "ncy\022\007\n\003EUR\020\000\022\007\n\003USD\020\001\022\007\n\003BTC\020\002\022\007\n\003ETH\020\003*" +
      "\031\n\004Side\022\007\n\003BUY\020\000\022\010\n\004SELL\020\001B\031\n\025gbdevw.col" +
      "ibri.domainP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_gbdevw_colibri_domain_Match_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gbdevw_colibri_domain_Match_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gbdevw_colibri_domain_Match_descriptor,
        new java.lang.String[] { "Timestamp", "Id", "Unit", "Quote", "Price", "Size", "Side", });
    internal_static_gbdevw_colibri_domain_Ticker_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gbdevw_colibri_domain_Ticker_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gbdevw_colibri_domain_Ticker_descriptor,
        new java.lang.String[] { "Timestamp", "Id", "Unit", "Quote", "LastTradePrice", "LastTradeSize", "LastTradeSide", "BestBid", "BestAsk", });
    internal_static_gbdevw_colibri_domain_OHLCV_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_gbdevw_colibri_domain_OHLCV_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gbdevw_colibri_domain_OHLCV_descriptor,
        new java.lang.String[] { "PeriodStart", "Unit", "Quote", "PeriodDuration", "Open", "High", "Low", "Close", "Volume", });
    internal_static_gbdevw_colibri_domain_MACD_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_gbdevw_colibri_domain_MACD_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gbdevw_colibri_domain_MACD_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "Macd", "Signal", });
    internal_static_gbdevw_colibri_domain_ROC_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_gbdevw_colibri_domain_ROC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gbdevw_colibri_domain_ROC_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "XPeriod", "Roc", "Resistance", "Support", });
    internal_static_gbdevw_colibri_domain_RSI_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_gbdevw_colibri_domain_RSI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gbdevw_colibri_domain_RSI_descriptor,
        new java.lang.String[] { "Timestamp", "Unit", "Quote", "XPeriod", "Rsi", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
