// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package gbdevw.colibri.domain;

public interface OHLCVOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gbdevw.colibri.domain.OHLCV)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 periodStart = 1;</code>
   * @return The periodStart.
   */
  long getPeriodStart();

  /**
   * <code>.gbdevw.colibri.domain.Currency unit = 2;</code>
   * @return The enum numeric value on the wire for unit.
   */
  int getUnitValue();
  /**
   * <code>.gbdevw.colibri.domain.Currency unit = 2;</code>
   * @return The unit.
   */
  gbdevw.colibri.domain.Currency getUnit();

  /**
   * <code>.gbdevw.colibri.domain.Currency quote = 3;</code>
   * @return The enum numeric value on the wire for quote.
   */
  int getQuoteValue();
  /**
   * <code>.gbdevw.colibri.domain.Currency quote = 3;</code>
   * @return The quote.
   */
  gbdevw.colibri.domain.Currency getQuote();

  /**
   * <code>uint64 periodDuration = 4;</code>
   * @return The periodDuration.
   */
  long getPeriodDuration();

  /**
   * <code>double open = 5;</code>
   * @return The open.
   */
  double getOpen();

  /**
   * <code>double high = 6;</code>
   * @return The high.
   */
  double getHigh();

  /**
   * <code>double low = 7;</code>
   * @return The low.
   */
  double getLow();

  /**
   * <code>double close = 8;</code>
   * @return The close.
   */
  double getClose();

  /**
   * <code>double volume = 9;</code>
   * @return The volume.
   */
  double getVolume();
}
