// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package gbdevw.colibri.domain;

/**
 * <pre>
 * Relative Strength Index
 * timestamp : The number of milliseconds from the epoch of 1970-01-01T00:00:00Z. - When the indicator is produced
 * unit : Unit Currency (Ex : BTC, ETH)
 * quote : Quote Currency (Ex : EUR, USD)
 * xPeriod : Number of candles used to produce the indicator
 * rsi : RSI value
 * </pre>
 *
 * Protobuf type {@code gbdevw.colibri.domain.RSI}
 */
public  final class RSI extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gbdevw.colibri.domain.RSI)
    RSIOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RSI.newBuilder() to construct.
  private RSI(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RSI() {
    unit_ = 0;
    quote_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RSI();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RSI(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            timestamp_ = input.readUInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            unit_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            quote_ = rawValue;
            break;
          }
          case 32: {

            xPeriod_ = input.readUInt32();
            break;
          }
          case 41: {

            rsi_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return gbdevw.colibri.domain.Domain.internal_static_gbdevw_colibri_domain_RSI_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return gbdevw.colibri.domain.Domain.internal_static_gbdevw_colibri_domain_RSI_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            gbdevw.colibri.domain.RSI.class, gbdevw.colibri.domain.RSI.Builder.class);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_;
  /**
   * <code>uint64 timestamp = 1;</code>
   * @return The timestamp.
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int UNIT_FIELD_NUMBER = 2;
  private int unit_;
  /**
   * <code>.gbdevw.colibri.domain.Currency unit = 2;</code>
   * @return The enum numeric value on the wire for unit.
   */
  public int getUnitValue() {
    return unit_;
  }
  /**
   * <code>.gbdevw.colibri.domain.Currency unit = 2;</code>
   * @return The unit.
   */
  public gbdevw.colibri.domain.Currency getUnit() {
    @SuppressWarnings("deprecation")
    gbdevw.colibri.domain.Currency result = gbdevw.colibri.domain.Currency.valueOf(unit_);
    return result == null ? gbdevw.colibri.domain.Currency.UNRECOGNIZED : result;
  }

  public static final int QUOTE_FIELD_NUMBER = 3;
  private int quote_;
  /**
   * <code>.gbdevw.colibri.domain.Currency quote = 3;</code>
   * @return The enum numeric value on the wire for quote.
   */
  public int getQuoteValue() {
    return quote_;
  }
  /**
   * <code>.gbdevw.colibri.domain.Currency quote = 3;</code>
   * @return The quote.
   */
  public gbdevw.colibri.domain.Currency getQuote() {
    @SuppressWarnings("deprecation")
    gbdevw.colibri.domain.Currency result = gbdevw.colibri.domain.Currency.valueOf(quote_);
    return result == null ? gbdevw.colibri.domain.Currency.UNRECOGNIZED : result;
  }

  public static final int XPERIOD_FIELD_NUMBER = 4;
  private int xPeriod_;
  /**
   * <code>uint32 xPeriod = 4;</code>
   * @return The xPeriod.
   */
  public int getXPeriod() {
    return xPeriod_;
  }

  public static final int RSI_FIELD_NUMBER = 5;
  private double rsi_;
  /**
   * <code>double rsi = 5;</code>
   * @return The rsi.
   */
  public double getRsi() {
    return rsi_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != 0L) {
      output.writeUInt64(1, timestamp_);
    }
    if (unit_ != gbdevw.colibri.domain.Currency.EUR.getNumber()) {
      output.writeEnum(2, unit_);
    }
    if (quote_ != gbdevw.colibri.domain.Currency.EUR.getNumber()) {
      output.writeEnum(3, quote_);
    }
    if (xPeriod_ != 0) {
      output.writeUInt32(4, xPeriod_);
    }
    if (rsi_ != 0D) {
      output.writeDouble(5, rsi_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, timestamp_);
    }
    if (unit_ != gbdevw.colibri.domain.Currency.EUR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, unit_);
    }
    if (quote_ != gbdevw.colibri.domain.Currency.EUR.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, quote_);
    }
    if (xPeriod_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, xPeriod_);
    }
    if (rsi_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, rsi_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof gbdevw.colibri.domain.RSI)) {
      return super.equals(obj);
    }
    gbdevw.colibri.domain.RSI other = (gbdevw.colibri.domain.RSI) obj;

    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (unit_ != other.unit_) return false;
    if (quote_ != other.quote_) return false;
    if (getXPeriod()
        != other.getXPeriod()) return false;
    if (java.lang.Double.doubleToLongBits(getRsi())
        != java.lang.Double.doubleToLongBits(
            other.getRsi())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + UNIT_FIELD_NUMBER;
    hash = (53 * hash) + unit_;
    hash = (37 * hash) + QUOTE_FIELD_NUMBER;
    hash = (53 * hash) + quote_;
    hash = (37 * hash) + XPERIOD_FIELD_NUMBER;
    hash = (53 * hash) + getXPeriod();
    hash = (37 * hash) + RSI_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getRsi()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static gbdevw.colibri.domain.RSI parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gbdevw.colibri.domain.RSI parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gbdevw.colibri.domain.RSI parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gbdevw.colibri.domain.RSI parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gbdevw.colibri.domain.RSI parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static gbdevw.colibri.domain.RSI parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static gbdevw.colibri.domain.RSI parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gbdevw.colibri.domain.RSI parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static gbdevw.colibri.domain.RSI parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static gbdevw.colibri.domain.RSI parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static gbdevw.colibri.domain.RSI parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static gbdevw.colibri.domain.RSI parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(gbdevw.colibri.domain.RSI prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Relative Strength Index
   * timestamp : The number of milliseconds from the epoch of 1970-01-01T00:00:00Z. - When the indicator is produced
   * unit : Unit Currency (Ex : BTC, ETH)
   * quote : Quote Currency (Ex : EUR, USD)
   * xPeriod : Number of candles used to produce the indicator
   * rsi : RSI value
   * </pre>
   *
   * Protobuf type {@code gbdevw.colibri.domain.RSI}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gbdevw.colibri.domain.RSI)
      gbdevw.colibri.domain.RSIOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gbdevw.colibri.domain.Domain.internal_static_gbdevw_colibri_domain_RSI_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gbdevw.colibri.domain.Domain.internal_static_gbdevw_colibri_domain_RSI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gbdevw.colibri.domain.RSI.class, gbdevw.colibri.domain.RSI.Builder.class);
    }

    // Construct using gbdevw.colibri.domain.RSI.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timestamp_ = 0L;

      unit_ = 0;

      quote_ = 0;

      xPeriod_ = 0;

      rsi_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return gbdevw.colibri.domain.Domain.internal_static_gbdevw_colibri_domain_RSI_descriptor;
    }

    @java.lang.Override
    public gbdevw.colibri.domain.RSI getDefaultInstanceForType() {
      return gbdevw.colibri.domain.RSI.getDefaultInstance();
    }

    @java.lang.Override
    public gbdevw.colibri.domain.RSI build() {
      gbdevw.colibri.domain.RSI result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public gbdevw.colibri.domain.RSI buildPartial() {
      gbdevw.colibri.domain.RSI result = new gbdevw.colibri.domain.RSI(this);
      result.timestamp_ = timestamp_;
      result.unit_ = unit_;
      result.quote_ = quote_;
      result.xPeriod_ = xPeriod_;
      result.rsi_ = rsi_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof gbdevw.colibri.domain.RSI) {
        return mergeFrom((gbdevw.colibri.domain.RSI)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(gbdevw.colibri.domain.RSI other) {
      if (other == gbdevw.colibri.domain.RSI.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.unit_ != 0) {
        setUnitValue(other.getUnitValue());
      }
      if (other.quote_ != 0) {
        setQuoteValue(other.getQuoteValue());
      }
      if (other.getXPeriod() != 0) {
        setXPeriod(other.getXPeriod());
      }
      if (other.getRsi() != 0D) {
        setRsi(other.getRsi());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      gbdevw.colibri.domain.RSI parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (gbdevw.colibri.domain.RSI) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>uint64 timestamp = 1;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>uint64 timestamp = 1;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 timestamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private int unit_ = 0;
    /**
     * <code>.gbdevw.colibri.domain.Currency unit = 2;</code>
     * @return The enum numeric value on the wire for unit.
     */
    public int getUnitValue() {
      return unit_;
    }
    /**
     * <code>.gbdevw.colibri.domain.Currency unit = 2;</code>
     * @param value The enum numeric value on the wire for unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnitValue(int value) {
      unit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.gbdevw.colibri.domain.Currency unit = 2;</code>
     * @return The unit.
     */
    public gbdevw.colibri.domain.Currency getUnit() {
      @SuppressWarnings("deprecation")
      gbdevw.colibri.domain.Currency result = gbdevw.colibri.domain.Currency.valueOf(unit_);
      return result == null ? gbdevw.colibri.domain.Currency.UNRECOGNIZED : result;
    }
    /**
     * <code>.gbdevw.colibri.domain.Currency unit = 2;</code>
     * @param value The unit to set.
     * @return This builder for chaining.
     */
    public Builder setUnit(gbdevw.colibri.domain.Currency value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      unit_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.gbdevw.colibri.domain.Currency unit = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUnit() {
      
      unit_ = 0;
      onChanged();
      return this;
    }

    private int quote_ = 0;
    /**
     * <code>.gbdevw.colibri.domain.Currency quote = 3;</code>
     * @return The enum numeric value on the wire for quote.
     */
    public int getQuoteValue() {
      return quote_;
    }
    /**
     * <code>.gbdevw.colibri.domain.Currency quote = 3;</code>
     * @param value The enum numeric value on the wire for quote to set.
     * @return This builder for chaining.
     */
    public Builder setQuoteValue(int value) {
      quote_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.gbdevw.colibri.domain.Currency quote = 3;</code>
     * @return The quote.
     */
    public gbdevw.colibri.domain.Currency getQuote() {
      @SuppressWarnings("deprecation")
      gbdevw.colibri.domain.Currency result = gbdevw.colibri.domain.Currency.valueOf(quote_);
      return result == null ? gbdevw.colibri.domain.Currency.UNRECOGNIZED : result;
    }
    /**
     * <code>.gbdevw.colibri.domain.Currency quote = 3;</code>
     * @param value The quote to set.
     * @return This builder for chaining.
     */
    public Builder setQuote(gbdevw.colibri.domain.Currency value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      quote_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.gbdevw.colibri.domain.Currency quote = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuote() {
      
      quote_ = 0;
      onChanged();
      return this;
    }

    private int xPeriod_ ;
    /**
     * <code>uint32 xPeriod = 4;</code>
     * @return The xPeriod.
     */
    public int getXPeriod() {
      return xPeriod_;
    }
    /**
     * <code>uint32 xPeriod = 4;</code>
     * @param value The xPeriod to set.
     * @return This builder for chaining.
     */
    public Builder setXPeriod(int value) {
      
      xPeriod_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 xPeriod = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearXPeriod() {
      
      xPeriod_ = 0;
      onChanged();
      return this;
    }

    private double rsi_ ;
    /**
     * <code>double rsi = 5;</code>
     * @return The rsi.
     */
    public double getRsi() {
      return rsi_;
    }
    /**
     * <code>double rsi = 5;</code>
     * @param value The rsi to set.
     * @return This builder for chaining.
     */
    public Builder setRsi(double value) {
      
      rsi_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double rsi = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRsi() {
      
      rsi_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gbdevw.colibri.domain.RSI)
  }

  // @@protoc_insertion_point(class_scope:gbdevw.colibri.domain.RSI)
  private static final gbdevw.colibri.domain.RSI DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new gbdevw.colibri.domain.RSI();
  }

  public static gbdevw.colibri.domain.RSI getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RSI>
      PARSER = new com.google.protobuf.AbstractParser<RSI>() {
    @java.lang.Override
    public RSI parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RSI(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RSI> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RSI> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public gbdevw.colibri.domain.RSI getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

