// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package gbdevw.colibri.domain;

public interface RSIOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gbdevw.colibri.domain.RSI)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>.gbdevw.colibri.domain.Currency unit = 2;</code>
   * @return The enum numeric value on the wire for unit.
   */
  int getUnitValue();
  /**
   * <code>.gbdevw.colibri.domain.Currency unit = 2;</code>
   * @return The unit.
   */
  gbdevw.colibri.domain.Currency getUnit();

  /**
   * <code>.gbdevw.colibri.domain.Currency quote = 3;</code>
   * @return The enum numeric value on the wire for quote.
   */
  int getQuoteValue();
  /**
   * <code>.gbdevw.colibri.domain.Currency quote = 3;</code>
   * @return The quote.
   */
  gbdevw.colibri.domain.Currency getQuote();

  /**
   * <code>uint32 xPeriod = 4;</code>
   * @return The xPeriod.
   */
  int getXPeriod();

  /**
   * <code>double rsi = 5;</code>
   * @return The rsi.
   */
  double getRsi();
}
