// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package gbdevw.colibri.domain;

public interface TickerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gbdevw.colibri.domain.Ticker)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 timestamp = 1;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>uint64 id = 2;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.gbdevw.colibri.domain.Currency unit = 3;</code>
   * @return The enum numeric value on the wire for unit.
   */
  int getUnitValue();
  /**
   * <code>.gbdevw.colibri.domain.Currency unit = 3;</code>
   * @return The unit.
   */
  gbdevw.colibri.domain.Currency getUnit();

  /**
   * <code>.gbdevw.colibri.domain.Currency quote = 4;</code>
   * @return The enum numeric value on the wire for quote.
   */
  int getQuoteValue();
  /**
   * <code>.gbdevw.colibri.domain.Currency quote = 4;</code>
   * @return The quote.
   */
  gbdevw.colibri.domain.Currency getQuote();

  /**
   * <code>double lastTradePrice = 5;</code>
   * @return The lastTradePrice.
   */
  double getLastTradePrice();

  /**
   * <code>double lastTradeSize = 6;</code>
   * @return The lastTradeSize.
   */
  double getLastTradeSize();

  /**
   * <code>.gbdevw.colibri.domain.Side lastTradeSide = 7;</code>
   * @return The enum numeric value on the wire for lastTradeSide.
   */
  int getLastTradeSideValue();
  /**
   * <code>.gbdevw.colibri.domain.Side lastTradeSide = 7;</code>
   * @return The lastTradeSide.
   */
  gbdevw.colibri.domain.Side getLastTradeSide();

  /**
   * <code>double bestBid = 8;</code>
   * @return The bestBid.
   */
  double getBestBid();

  /**
   * <code>double bestAsk = 9;</code>
   * @return The bestAsk.
   */
  double getBestAsk();
}
